name: flame_realtime_shooting
description: Multiplayer shooting game using Flutter, Flame and Supabase.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.0.0
  flame: ^1.8.2
  flame_audio: ^2.0.5
  uuid: ^3.0.7
  auto_orientation: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
